baseURL = 'http://12buntu.github.io/'
languageCode = 'en-us'
title = "12buntu"
theme = '12buntu'
disablePathToLower = true

[Params]
googlefonts = "https://fonts.googleapis.com/css?family=Fira+Mono|Noto+Sans|Fira+Code"
